baseURL: https://mitszo.org/
title: mitszo's portfolio
pagination:
  pagerSize: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
# enableInlineShortcodes: true
# enableEmoji: true
# pygmentsUseClasses: true

minify:
    disableXML: true
    minifyOutput: true

params:
    env: production
    title: mitszo's portfolio
    description: mitszo's portfolio
    author: Me

    # disableThemeToggle: true
    # images: ["<link or path of image for opengraph, twitter-cards>"]
    DateFormat: "2006-01-02"
    defaultTheme: auto
    defaultThemeToggle: true

    ShowShareButtons: true
    ShowReadingTime: true
    displayFullLangName: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true
    comments: false

    profileMode:
        # Disable to populate home page with 'mainSections' content
        enabled: true
        title: mitszo
        description: |

          Hello.

        imageUrl: "/images/profile.jpg"
        imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        buttons:
        #     - name: Don't click me
        #       url: https://www.youtube.com/watch?v=dQw4w9WgXcQ
    mainSections:
      - contact

    socialIcons:
        - name: github
          url: "https://github.com/mitszo"
        - name: flickr
          url: "https://flickr.com/mitszo"
        - name: instagram
          url: "https://instagram.com/mitszo"
        - name: keybase
          url: "https://keybase.io/mitszo"
        - name: bluesky
          url: "https://bsky.app/profile/mitszo.org"

      # add more social icons. find more in svg.html file
      # - name: youtube
      #   url: yoururl
      # - name: twitter
      #   url: yoururl
      # - name: facebook
      #   url: yoururl

    analytics:
      google:
        SiteVerificationTag: "G-WN2C07CFWP"

    # change favicon in images folder (icon for web tab)
    assets:
          favicon: "/images/favicon.ico"
          favicon16x16: "/images/favicon-16x16.png"
          favicon32x32: "/images/favicon-32x32.png"
          apple_touch_icon: "/images/apple-touch-icon.png"
          safari_pinned_tab: "/images/apple-touch-icon.png"


menu:
    main:
      - identifier: contact
        name: Contact
        url: /contact/
        weight: 30

      - identifier: work
        name: Work
        url: /work/
        weight: 20

      #  - name: Articles
      #    url: /articles/
      #    weight: 20
      #  - name: Projects
      #    url: /projects/
      #    weight: 15

     # - name: Categories
        #   url: /categories/
        #   weight: 10
        # - name: new Tab
        #   url: /newtab/
        #   weight: defines order of tabs
   





